[book]
authors = ["kassandra, mikki"]
language = "en"
multilingual = false
src = "src"
title = "Beast Mode"

[output.html]
default-theme = "navy"
preferred-dark-theme = "ayu"
no-section-label = true

[output.html.fold]
enable = true
level = 0
